spring:
  datasource:
    url: jdbc:mysql://192.168.187.134:3306/sfg_prod
    username: sfg_prod_user
    password: alex77
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false